### ISSUE TITLE
Use of time variable in differential equations prepared with compile.ode

### ISSUE THREAD

**Issue by jranke** [karlines/ccSolve#1]
Dear Karline,

thank you for this nice package. I am currently testing its use in my kinetic evaluation package, and I can already say that ccSolve is very convenient to use and really lowers the barrier for people like me to use compiled functions in their R code! I can successfully employ it in cases where time is not in the right hand side of the equation and it does give a very nice speedup.

However, I did not find anything in the documentation if and how the time variable can be used in the differential equations?

As a simple example, I would like to be able to generate a compiled version of C code fragments like:

```
f[0] = - (alpha/beta) * ((t/beta) + 1)^-1 * y[0];
```

When this is compiled using compile.ode, I get

```
file19e3223c88a6.c: In function ‘func’:
file19e3223c88a6.c:19:28: error: invalid operands to binary / (have ‘double *’ and ‘double’)   
 f[0] = - (alpha/beta) * ((t/beta) + 1)^-1 * y[0]; 
```

``` C
Program source:
  1: #include <R.h>
  2: 
  3:  
  4:  static double parms[2];
  5: #define alpha parms[0]
  6: #define beta parms[1]
  7: 
  8: void initpar(void (* odeparms)(int *, double *)){
  9:     int N =2;
 10:     odeparms(&N, parms);
 11: }
 12: 
 13: void func ( int * n, double * t, double * y, double * f, double * rpar, int * ipar ) {
 14: 
 15:   
 16:   
 17:  
 18:    
 19: f[0] = - (alpha/beta) * ((t/beta) + 1)^-1 * y[0];   
 20: 
 21: }
```

I do not have enough knowledge in C to understand the problem in the C code. Is it related to the fact that t is declared as `double *` but not `alpha` and `beta`? Would you be so kind to help me understand? In addition, would there be a way to use `time` as the time variable in the functions by some kind of variable declaration in the beginning? Otherwise, I would have difficulties to safely translate my autogenerated differential equation code to use `t`.

Kind regards,

Johannes

**Comment by karlines** [comment]
Johannes, As far as I can remember, i have not yet posted this package on CRAN? I also have two versions now, one on R-forge, one on gitHub. Where did you obtain this one?

You have to use *t, rahter than t.

You could use in the beinnign of the code:
double time = *t;
which would then allow you to use time rather than *t,

Hope it helps,

Karline

**Comment by jranke** [comment]
Karline,

thanks for your quick reply - I am really excited as this would be a real 
performance booster for the solution of the differential equations I am 
generating with mkin!

I read about your contributions to the inline package in Dirks blog, so I 
looked at your github account and found ccSolve which exactly fits my needs.

I forked your repository on github. I had to disable vignette generation in R 
CMD build to get it to build, but then it worked fine.

Do you sync your github project with r-forge? For my mkin and gmkin packages 
(which are heavily based on FME) I have a Makefile which takes care of 
submitting the changes in the git working copy to the r-forge svn.

Kind regards,

Johannes

Am Freitag, 17. April 2015, 06:09:43 schrieb karline soetaert:

**Comment by jranke** [comment]
Wow, I can just put specify `declaration = "double time = *t;"` to the call to
compile.ode, and I can use time in the function!

So it works for another model with time on the right hand side. For the code I showed you, it seems I only need to adapt the syntax for the power function,
as the compiler complains about

```
Fehler in compileCode(f, code, language, verbose) : 
  Compilation ERROR, function(s)/method(s) not created! file25a5b75e11d.c: In function ‘func’:
file25a5b75e11d.c:19:42: error: invalid operands to binary ^ (have ‘double’ and ‘double’)
 f[0] = - (alpha/beta) * ((time/beta) + 1)^-1 * y[0];   
                                          ^
```

**Comment by jranke** [comment]
OK, I just used 1/term instead of term^-1 - everything seems to work, thanks a lot!
